---
title: "Philippines Field Protocols"
author: "Michelle Stuart"
date: "6/7/2017"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mayoral Visits and University President Courtesy call

The first full day in Leyte, visit the Mayors offices of Albuera and Baybay.  If the PIC forms still need to be signed, bring those along.  Also take a photo of researcher with the office staff to document the visit.  

Email the university president before departing the US to arrange a courtesy call for the same day.

## Standard dive gear
For each diver pack:

* Wetsuit/diveskin
+ Fins
+ Booties
+ BC
+ Regulator
+ Weights (these can be left on the boat)
+ 1 tank per planned dive

## HOBO retrieval and replacement

As a first dive of the season, replace the HOBO temperature data loggers at Visca.  This is a nice way to check out gear close to the marine lab and do a test dive to make sure everything is working as expected.

Before the dive,

* connect the base station to the computer
* connect the hobo to the base station
+ Open the software
+ Click “launch device” first icon on the left 
+ First device launch now and change interval to 30 minutes; 
+ second device launch on time 15 minutes later.
+ Take a screen shot of the launch.

In addition to standard dive gear, bring:

* gloves for handling hydroid covered PVC housing
+ scissors for cutting present zipties
+ launched HOBO sensors
+ fresh zipies
+ slate with paper and pencil for noting which serial number HOBO went in which location, and which was taken from which location.

The first HOBO is located just south of the resort tower at 10.74373, 124.78668.
The second HOBO is located about 10m to the SW, 10.74364, 124.78665.

Turn of the old HOBOS by clicking “read out device”.  Save the files.

Clean the old hobos by running under water and scrubbing with a test tube brush.  If they resist, let them dry out for a month or a year and try again. 

## Drifter 
Plot the deployment locations on the GPS.  In 2017 they were north, south, west, west center, center and east.

Unscrew cap to start microstar transmission, screw on drogue cap and open drogue until it clicks.

Navigate boat to deployment locataions and drop in the drifters.

## Clownfish surveys
Team backs off until anemone surveyor has a chance to observe.

Anemone surveyor:
1. searches adjacent area for anemone tag (anemone could have moved a few feet since last encounter)
2. records time, species, size of anemone, tag number if present
3. watches anemone and counts number of fish and estimate sizes (same procedure regardless of species)
4. records spp of fish, estimate sizes
5. Adds tag after the fact if one was missing or if there was only one zip tie tag (old system tag)
6. Flags anemone with flagging tape that it is ready to be hunted if APCL were present.

Fish catcher:
1. waits for flagging tape to indicate anemone is ready for fish capture, ok to chase fish if they flee the area
2. catches all fish of desired size range and places in holding vessel adjacent to anemone
3. can move on to next anemone if anemone surveyor has flagged it

Fish processing team (2 people):
once the fish catcher has moved to the next anemone, begins processing fish in the holding vessel
1. measure the fish and photograph on the gridded slate
2. Record size and tail color
3. Scan for pit tag, if present, 
    1. record and release fish
4. If no pit tag is present, 
    1. collect fin clip and record sample id
    2. insert pit tag and record tag id
    3. release fish
5. Repeat until all fish in the vessel have been processed.
6. Move on to next holding vessel.
